<a href="https://colab.research.google.com/github/Rukhsar-Nisar/20SW137_DS-A_LAB_TASKS/blob/main/20SW137(LAB_04).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#Task_01
import numpy as np
Even_Numbers = np.arange(2, 33, 2)
Y = Even_Numbers.reshape(4, 4)
print(Y)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [6]:
#TASK02
import numpy as np
A = np.arange(1, 26).reshape(5, 5)
B = A[A % 2 != 0]

print(A)
print(B)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [9]:
#TASK03
import numpy as np
Col_values = np.arange(1, 5).reshape(-1, 1)
A = Col_values * np.ones((4, 4))
print(A)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [11]:
#TASK04
from google.colab import drive
drive.mount('/NumPy.ipnyb')

import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)

# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

Mounted at /NumPy.ipnyb
(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[-1.06986311  1.3885015  -0.1324727  ... -0.88381175 -0.75916715
  -0.22035062]
 [-1.24893056  0.89443098 -0.28731894 ...  1.02273825  1.58109344
  -1.65180512]
 [-0.41237116  1.40695227 -1.31729163 ... -1.70150212  1.2118692
   1.27218114]
 ...
 [-0.38298223 -1.15428747  0.24798659 ... -1.23932931 -1.16634902
   1.56071856]
 [-1.19151962  1.58189287  0.81622323 ...  0.25802697  1.14147504
  -1.22215816]
 [ 0.39206546  0.85137919  0.93043108 ...  1.245111    1.55762872
  -1.43768368]]
Average of all values in X_norm: -1.2789769243681803e-17
Average of minimum values in each column of X_norm: -1.744410093559311
Average of maximum values in each column of X_norm: 1.725759686092747
Random permutation of row indices: [941 926 413 827 842 110  16 730 530 283 756 962 921 484  58 449 187 689
  36 152 305 102 170 256 516 363 460 326  38 307 602 440 587 687 309 566
 666 552 855 246  18 368 9